spring:
  datasource:
    url: jdbc:h2:./sauron_db/sauron;MODE=PostgreSQL
    username: sauron
    password: sauron
  h2:
    console:
      path: /console/

logging:
  level:
    org.springframework.web.servlet: INFO
    Exposed: DEBUG



app:
  appName: "SAURON"